function getData() {
  return [
    { category: 'a', value: Math.random() * 100, custom_field: 80, x: "learning" },
    { category: 'a', value: Math.random() * 100, custom_field: 56, x: "includes" },
    { category: 'b', value: Math.random() * 100, custom_field: 44, x: "lists" },
    { category: 'b', value: Math.random() * 100, custom_field: 40, x: "meaning" },
    { category: 'c', value: Math.random() * 100, custom_field: 36, x: "useful" },
    { category: 'c', value: Math.random() * 100, custom_field: 32, x: "different" },
    { category: 'a', value: Math.random() * 100, custom_field: 80, x: "learning" },
    { category: 'a', value: Math.random() * 100, custom_field: 56, x: "includes" },
    { category: 'b', value: Math.random() * 100, custom_field: 44, x: "lists" },
    { category: 'b', value: Math.random() * 100, custom_field: 40, x: "meaning" },
    { category: 'c', value: Math.random() * 100, custom_field: 36, x: "useful" },
    { category: 'c', value: Math.random() * 100, custom_field: 32, x: "different" },
    { category: 'a', value: Math.random() * 100, custom_field: 80, x: "learning" },
    { category: 'a', value: Math.random() * 100, custom_field: 56, x: "includes" },
    { category: 'b', value: Math.random() * 100, custom_field: 44, x: "lists" },
    { category: 'b', value: Math.random() * 100, custom_field: 40, x: "meaning" },
    { category: 'c', value: Math.random() * 100, custom_field: 36, x: "useful" },
    { category: 'c', value: Math.random() * 100, custom_field: 32, x: "different" },
    { category: 'a', value: Math.random() * 100, custom_field: 80, x: "learning" },
    { category: 'a', value: Math.random() * 100, custom_field: 56, x: "includes" },
    { category: 'b', value: Math.random() * 100, custom_field: 44, x: "lists" },
    { category: 'b', value: Math.random() * 100, custom_field: 40, x: "meaning" },
    { category: 'c', value: Math.random() * 100, custom_field: 36, x: "useful" },
    { category: 'c', value: Math.random() * 100, custom_field: 32, x: "different" },
    { category: 'a', value: Math.random() * 100, custom_field: 80, x: "learning" },
    { category: 'a', value: Math.random() * 100, custom_field: 56, x: "includes" },
    { category: 'b', value: Math.random() * 100, custom_field: 44, x: "lists" },
    { category: 'b', value: Math.random() * 100, custom_field: 40, x: "meaning" },
    { category: 'c', value: Math.random() * 100, custom_field: 36, x: "useful" },
    { category: 'c', value: Math.random() * 100, custom_field: 32, x: "different" },
  ];
}